JUNOS:
  - test_isis_adjacency.yml
  - test_ldp_interface.yml
  - test_ldp_neighbor.yml
  - test_ldp_session.yml
  - test_pim_interfaces.yml
  - test_pim_neighbors.yml
  - test_rsvp_interface.yml
  - test_task_replication.yml
  - test_bgp_summary.yml

IOS:
  - test_isis_neighbor.yml

XR:
  - test_isis_neighbor.yml

TiMOS:
  - test_router_isis_adjacency.yml
